const PDFDocument = require("pdfkit");

const generateAnalysisPDF = (analysis, res) => {
  const doc = new PDFDocument({
    size: "A4",
    margin: 50,
  });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="resume-analysis-${analysis._id}.pdf"`
  );

  doc.pipe(res);

  // Header
  doc
    .fontSize(24)
    .font("Helvetica-Bold")
    .text("AI Resume Gap Analyzer");

  doc
    .moveDown(0.5)
    .fontSize(12)
    .font("Helvetica")
    .fillColor("#666666")
    .text("Professional Resume Analysis Report");

  doc.moveDown(1);

  // Job Information
  doc
    .fillColor("#000000")
    .fontSize(16)
    .font("Helvetica-Bold")
    .text("Job Details");

  doc.moveDown(0.4);

  doc
    .fontSize(11)
    .font("Helvetica")
    .text(`Position: ${analysis.jobDescription?.title || "N/A"}`)
    .text(`Company: ${analysis.jobDescription?.company || "N/A"}`)
    .text(`Resume: ${analysis.resume?.originalName || "N/A"}`);

  doc.moveDown(1);

  // Scores
  doc
    .fontSize(16)
    .font("Helvetica-Bold")
    .text("Performance Scores");

  doc.moveDown(0.5);

  doc
    .fontSize(13)
    .font("Helvetica")
    .text(`ATS Score: ${analysis.atsScore ?? 0}%`)
    .text(`Job Compatibility: ${analysis.compatibilityScore ?? 0}%`);

  doc.moveDown(1);

  // Resume Summary
  addSection(doc, "Resume Summary");

  doc
    .fontSize(11)
    .font("Helvetica")
    .text(analysis.resumeSummary || "No summary available.");

  // Matched Skills
  addSection(doc, "Matched Skills");

  addList(
    doc,
    analysis.matchedSkills,
    "No matched skills found."
  );

  // Missing Skills
  addSection(doc, "Missing Skills");

  addList(
    doc,
    analysis.missingSkills,
    "No significant missing skills found."
  );

  // Strengths
  addSection(doc, "Strengths");

  addList(
    doc,
    analysis.strengths,
    "No strengths available."
  );

  // Weaknesses
  addSection(doc, "Weaknesses");

  addList(
    doc,
    analysis.weaknesses,
    "No weaknesses available."
  );

  // Roadmap
  addSection(doc, "Personalized Learning Roadmap");

  if (analysis.roadmap?.length) {
    analysis.roadmap.forEach((item, index) => {
      doc
        .fontSize(12)
        .font("Helvetica-Bold")
        .text(`${index + 1}. ${item.skill || "Skill"}`);

      doc
        .fontSize(10)
        .font("Helvetica")
        .text(`Priority: ${item.priority || "Medium"}`)
        .text(`Why it matters: ${item.reason || "N/A"}`);

      if (item.resources?.length) {
        doc.text("Resources:");

        item.resources.forEach((resource) => {
          doc.text(`• ${resource}`);
        });
      }

      doc.moveDown(0.6);
    });
  } else {
    doc
      .fontSize(11)
      .font("Helvetica")
      .text("No roadmap available.");
  }

  // Footer
  doc
    .moveDown(1)
    .fontSize(9)
    .fillColor("#777777")
    .text(
      "Generated by SkillTrace",
      {
        align: "center",
      }
    );

  doc.end();
};

const addSection = (doc, title) => {
  doc
    .moveDown(1)
    .fillColor("#000000")
    .fontSize(16)
    .font("Helvetica-Bold")
    .text(title);

  doc.moveDown(0.4);
};

const addList = (doc, items, emptyMessage) => {
  if (!items?.length) {
    doc
      .fontSize(11)
      .font("Helvetica")
      .text(emptyMessage);

    return;
  }

  items.forEach((item) => {
    doc
      .fontSize(11)
      .font("Helvetica")
      .text(`• ${item}`);
  });
};

module.exports = {
  generateAnalysisPDF,
};